/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SyllabusImport } from './routes/Syllabus'
import { Route as StaffImport } from './routes/Staff'
import { Route as LoginImport } from './routes/Login'
import { Route as InquiryImport } from './routes/Inquiry'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SyllabusRoute = SyllabusImport.update({
  path: '/Syllabus',
  getParentRoute: () => rootRoute,
} as any)

const StaffRoute = StaffImport.update({
  path: '/Staff',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

const InquiryRoute = InquiryImport.update({
  path: '/Inquiry',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Inquiry': {
      id: '/Inquiry'
      path: '/Inquiry'
      fullPath: '/Inquiry'
      preLoaderRoute: typeof InquiryImport
      parentRoute: typeof rootRoute
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/Staff': {
      id: '/Staff'
      path: '/Staff'
      fullPath: '/Staff'
      preLoaderRoute: typeof StaffImport
      parentRoute: typeof rootRoute
    }
    '/Syllabus': {
      id: '/Syllabus'
      path: '/Syllabus'
      fullPath: '/Syllabus'
      preLoaderRoute: typeof SyllabusImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  InquiryRoute,
  LoginRoute,
  StaffRoute,
  SyllabusRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/Inquiry",
        "/Login",
        "/Staff",
        "/Syllabus"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/Inquiry": {
      "filePath": "Inquiry.jsx"
    },
    "/Login": {
      "filePath": "Login.jsx"
    },
    "/Staff": {
      "filePath": "Staff.jsx"
    },
    "/Syllabus": {
      "filePath": "Syllabus.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
